### ISSUE TITLE
Carly Issues on 6/2/20

### ISSUE THREAD

**Issue by clm043** [moravianlives/ML#219]
@djakacki There are conflicts between my branch and the Charlesworth memoir, preventing my branch from being merged with the master. #218 Ann Cannings and Anna Rosina Anderson seem to be pointing to the incorrect style sheet. I am also having a hard time getting to the encoding Trello board (maybe the website is down).

**Comment by djakacki** [comment]
Charlesworth resolved; checked that Ann Cannings and Anna Rosina Anderson are pointing at correct stylesheet.
Trello is alive again.
