### ISSUE TITLE
Mary Hinchcliffe

### ISSUE THREAD

**Issue by clm043** [moravianlives/ML#372]
There is a problem with the line breaks on the 9th line of the first page in the Mary Hinchcliffe memoir @djakacki

**Comment by djakacki** [comment]
@clm043 can you take a screenshot of what you see? It looks ok from my end.
Thanks.

**Comment by clm043** [comment]
<img width="960" alt="hinchcliffe" src="https://user-images.githubusercontent.com/44586494/88674451-d3d89300-d0b7-11ea-84f6-e42a5900b350.png">
